bases:
  - "configs/base.yaml"
  - "configs/g2p.yaml"

binarizer:
  phoneme_timing_data_dir: "data/phones"
  text_only_data_dir: "data/texts"
  vocabulary:
    global_symbols: [AP, SP, EP, GS, sil, br, pau, cl]
    stop_symbols: [AP, SP, EP, GS, sil, br, pau, cl]
    merged_groups: []
    peers: []

model: {}

training:
  loss: {}
  iterative_ranking:
    enabled: true
    rank_size: 4
    gamma: 0.9
    update_every_n_epochs: 1
  validation: {}
