bases:
  - "configs/base.yaml"
  - "configs/g2p.yaml"

binarizer:
  phoneme_timing_data_dir: "data/phones"
  text_only_data_dir: "data/texts"
  vocabulary:
    global_symbols: [AP, SP, EP, GS, sil, br, pau, cl]
    stop_symbols: [AP, SP, EP, GS, sil, br, pau, cl]
    merged_groups: []
    peers: []

model: {}

training:
  dataloader:
    aux_multiplier: 1.0
  augmentation:
    token_perturbation:
      enabled: false
      prob: 0.2
      p_sub: 0.05
    sequence_edit:
      enabled: false
      prob: 0.2
      p_sub: 0.03
      p_del: 0.02
      p_ins: 0.02
    time_stretching:
      enabled: false
  loss: {}
  validation: {}
